fileinfo['MAC_SNAPSHOT_URL'] = 'https://files.openscad.org/snapshots/OpenSCAD-2020.04.23.dmg'
fileinfo['MAC_SNAPSHOT_NAME'] = 'OpenSCAD 2020.04.23'
fileinfo['MAC_SNAPSHOT_SIZE'] = '25 MB'
fileinfo['MAC_SNAPSHOT_SHA256_URL'] = fileinfo['MAC_SNAPSHOT_URL'] + '.sha256'
fileinfo['MAC_SNAPSHOT_SHA512_URL'] = fileinfo['MAC_SNAPSHOT_URL'] + '.sha512'
