fileinfo['SRC_RELEASE_URL'] = 'https://files.openscad.org/openscad-2019.05.src.tar.gz'
fileinfo['SRC_RELEASE_NAME'] = 'OpenSCAD 2019.05'
fileinfo['SRC_RELEASE_SIZE'] = '14 MB'
fileinfo['SRC_RELEASE_ASC_URL'] = fileinfo['SRC_RELEASE_URL'] + '.asc'
fileinfo['SRC_RELEASE_SHA256_URL'] = fileinfo['SRC_RELEASE_URL'] + '.sha256'
fileinfo['SRC_RELEASE_SHA512_URL'] = fileinfo['SRC_RELEASE_URL'] + '.sha512'
